spring.application.name=url-shortner

#spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortner_db
#spring.datasource.username=postgres
#spring.datasource.password=1234

spring.datasource.url=${DB_URI:jdbc:postgresql://localhost:5432/url_shortner_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false