spring.application.name=url-shortner

#spring.datasource.url=jdbc:postgresql://dpg-d6vg57450q8c739kgph0-a.oregon-postgres.render.com/url_shortner_db_l2o6
#spring.datasource.username=url_shortner_db_l2o6_user
#spring.datasource.password=3rbxm1CsIY9M3MnALWG1VFtlknoNJZuQ


spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
